name: validate
on:
  schedule:
    - cron: '0 0 * * *'
  push:
jobs:
  validate:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Setup dependencies
      run: |
        echo '{"w3capikey":"${{ secrets.W3C_API_KEY }}","ghToken":"${{ secrets.W3C_GITHUB_TOKEN }}"}' > config.json
        npm ci --production
    - name: Run validate.js
      run: node validate.js > report.json
    - name: Run extract-rec-track.js
      run: node extract-rec-track.js > rec-track-repos.json
    - name: Run extract-horizontal-reviews.js
      run: node extract-horizontal-reviews.js > hr-repos.json
    - name: Commit changes
      run: |
        git config user.name "w3c-validate-repos-bot"
        git config user.email "<>"
        git add report.json rec-track-repos.json hr-repos.json
        git commit -m "Update report.json, rec-track-repos.json, hr-repos.json"
        git show
    - name: Push changes
      if: github.ref == 'refs/heads/master' && github.actor != 'dontcallmedom-bot'
      run: |
        git remote set-url --push origin https://x-access-token:${{ secrets.W3C_GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git push origin HEAD:master
